stages:
    - test:build
    - production:build

# ---

production:build:image:sshuttle:
    before_script:
        - 'export DOCKER_HOST=tcp://docker:2375'
        - 'docker login --password "${CI_REGISTRY_PASSWORD}" --username "${CI_REGISTRY_USER}" registry.gitlab.com'
        - 'docker login --password "${HUB_REGISTRY_PASSWORD}" --username "${HUB_REGISTRY_USER}"'
    image:
        entrypoint: ['']
        name: docker:stable
    only:
        - master
    retry:
        max: 2
    script:
        - 'docker build --pull --tag "${CI_REGISTRY_IMAGE}":latest src'
        - 'docker push "${CI_REGISTRY_IMAGE}":latest'
        - 'docker tag "${CI_REGISTRY_IMAGE}":latest "${HUB_REGISTRY_IMAGE}":latest'
        - 'docker push "${HUB_REGISTRY_IMAGE}":latest'
    services:
        - docker:stable-dind
    stage: production:build

test:build:image:sshuttle:
    before_script:
        - 'export DOCKER_HOST=tcp://docker:2375'
    image:
        entrypoint: ['']
        name: docker:stable
    only:
        - /^feature\/.*$/
    retry:
        max: 2
    script:
        - 'docker build --pull --tag "${CI_REGISTRY_IMAGE}":"${CI_COMMIT_REF_SLUG}" src'
        - 'docker push "${CI_REGISTRY_IMAGE}":"${CI_COMMIT_REF_SLUG}"'
    services:
        - docker:stable-dind
    stage: test:build
